# Generated by Django 4.0.4 on 2022-11-06 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_patient_registration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='photo_of_the_doctor',
            field=models.ImageField(blank=True, null=True, upload_to=None),
        ),
        migrations.AlterField(
            model_name='patient',
            name='registration_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
