# Generated by Django 4.0.4 on 2022-11-06 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_doctor_photo_of_the_doctor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='registration_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
